(** Chart.js bindings for line charts.

    These Bindings have partially been generated by a LLM. Only the parts used
    in this project have been reviewed / hand-crafted.s *)

open Brr

(** {1:color Color representation} *)

type color = Jstr.t
(** The type for color values (CSS color strings or rgba()). *)

val rgb : int -> int -> int -> color
(** [rgb r g b] creates an rgb color. *)

val rgba : int -> int -> int -> float -> color
(** [rgba r g b a] creates an rgba color with alpha in [0.0, 1.0]. *)

(** {1:objects Chart.js main types} *)

(** Dataset configuration for a line chart. *)
module Dataset : sig
  type t
  (** The type for [Chart.js] dataset objects. *)

  (**/**)

  include Jv.CONV with type t := t

  (**/**)

  val create :
    ?label:Jstr.t ->
    ?border_color:color ->
    ?background_color:color ->
    ?border_width:int ->
    ?border_dash:float list ->
    ?tension:float ->
    ?fill:bool ->
    ?point_radius:int ->
    data:float list ->
    unit ->
    t
  (** [create ~label ~data ()] creates a dataset with the given label and data
      points. *)

  val set_data : t -> float list -> unit
  val push_data : t -> float -> unit

  val set_border_color : t -> color -> unit
  (** [set_border_color d c] sets the line color. *)

  val set_background_color : t -> color -> unit
  (** [set_background_color d c] sets the fill color. *)

  val set_border_width : t -> int -> unit
  (** [set_border_width d w] sets the line width in pixels. *)

  val set_border_dash : t -> float list -> unit

  val set_tension : t -> float -> unit
  (** [set_tension d t] sets the line tension (0 = straight, 1 = curved). *)

  val set_fill : t -> bool -> unit
  (** [set_fill d b] enables or disables filling under the line. *)

  val set_point_radius : t -> int -> unit
  (** [set_pointRadius d r] sets the point radius. *)

  val to_jv : t -> Jv.t
  (** [to_jv d] converts to a JavaScript object. *)
end

(** Chart data (labels and datasets). *)
module Data : sig
  type t
  (** The type for [Chart.js] data objects. *)

  (**/**)

  include Jv.CONV with type t := t

  (**/**)

  val create : ?labels:Jstr.t list -> ?datasets:Dataset.t list -> unit -> t
  (** [create ~labels ()] creates an empty dataset container with optional
      labels. *)

  val add_dataset : t -> Dataset.t -> unit
  (** [add_dataset d s] adds a dataset to the chart data. *)

  val set_labels : t -> Jstr.t list -> unit
  val push_label : t -> Jstr.t -> unit

  val to_jv : t -> Jv.t
  (** [to_jv d] converts to a JavaScript object. *)
end

(** Chart configuration options. *)
module Options : sig
  type t
  (** The type for [Chart.js] options objects. *)

  (**/**)

  include Jv.CONV with type t := t

  (**/**)

  val create : ?responsive:bool -> ?maintainAspectRatio:bool -> unit -> t
  (** [create ~responsive ~maintainAspectRatio ()] creates options with
      defaults. [responsive] defaults to true, [maintainAspectRatio] to true. *)

  val set_responsive : t -> bool -> unit
  val set_maintain_aspect_ratio : t -> bool -> unit

  val to_jv : t -> Jv.t
  (** [to_jv o] converts to a JavaScript object. *)
end

(** The Chart object. *)
module Chart : sig
  type t
  (** The type for [Chart.js] chart objects. *)

  (**/**)

  include Jv.CONV with type t := t

  (**/**)

  val create :
    canvas:El.t ->
    chart_type:Jstr.t ->
    ?data:Data.t ->
    options:Options.t ->
    unit ->
    t
  (** [create ~canvas ~chart_type ?data ~options] creates a new Chart.
      [chart_type] should be "line" for line charts. *)

  val destroy : t -> unit
  (** [destroy c] removes the chart from the DOM and cleans up. *)

  val update : t -> unit
  (** [update c] refreshes the chart display. *)

  val set_data : t -> Data.t -> unit

  val get_data : t -> Data.t
  (** [get_data c] returns the chart's data object. *)

  val to_jv : t -> Jv.t
  (** [to_jv c] converts to its underlying JavaScript object. *)
end
