(** Bindings to the Grist plugin API

    Warning: A large part of this module has been generated by a LLM without
    careful review. *)

module Data : sig
  module Row_records : sig
    include Jv.CONV

    val by_row : t -> Jv.t
  end
end

module Access_token_result : sig
  include Jv.CONV

  val token : t -> Jstr.t
  val base_url : t -> Jstr.t
  val ttl_msec : t -> int option
end

module New_record : sig
  include Jv.CONV

  val v : ?fields:(Jstr.t * Jv.t) array -> unit -> t
end

module Record : sig
  include Jv.CONV

  val v : id:int -> ?fields:(Jstr.t * Jv.t) array -> unit -> t
end

module Add_or_update_record : sig
  include Jv.CONV

  val v :
    require:(Jstr.t * Jv.t) array ->
    ?require_id:int ->
    ?fields:(Jstr.t * Jv.t) array ->
    unit ->
    t
  (** [require] is the set of column/value pairs used to match an existing
      record. [require_id] may be used to additionally match by row id. [fields]
      contains the values to write. *)
end

module Op_options : sig
  include Jv.CONV

  val v : ?parse_strings:bool -> unit -> t
end

type on_many = All | None_ | First

module Upsert_options : sig
  include Jv.CONV

  val v :
    ?add:bool ->
    ?update:bool ->
    ?on_many:on_many ->
    ?allow_empty_require:bool ->
    ?parse_strings:bool ->
    unit ->
    t
end

module Table_operations : sig
  include Jv.CONV

  val create :
    t ->
    records:New_record.t list ->
    ?options:Op_options.t ->
    unit ->
    Jv.t Fut.or_error

  val destroy : t -> record_ids:int list -> unit Fut.or_error
  val get_table_id : t -> Jstr.t Fut.or_error

  val update :
    t ->
    records:Record.t list ->
    ?options:Op_options.t ->
    unit ->
    unit Fut.or_error

  val upsert :
    t ->
    records:Add_or_update_record.t list ->
    ?options:Upsert_options.t ->
    unit ->
    unit Fut.or_error
end

module View_API : sig
  include Jv.CONV

  val allow_select_by : t -> unit Fut.or_error

  val fetch_selected_record :
    t -> row_id:int -> ?options:Jv.t -> unit -> Jv.t Fut.or_error

  val fetch_selected_table : t -> ?options:Jv.t -> unit -> Jv.t Fut.or_error
  val set_cursor_pos : t -> pos:Jv.t -> unit Fut.or_error
  val set_selected_rows : t -> row_ids:Jv.t -> unit Fut.or_error
end

module Doc_API : sig
  include Jv.CONV

  val fetch_table : table_id:Jstr.t -> Data.Row_records.t Fut.or_error

  val fetch_selected_record :
    t -> row_id:int -> ?options:Jv.t -> unit -> Jv.t Fut.or_error

  val fetch_selected_table : t -> ?options:Jv.t -> unit -> Jv.t Fut.or_error
  val allow_select_by : t -> unit Fut.or_error
  val set_cursor_pos : t -> pos:Jv.t -> unit Fut.or_error
  val set_selected_rows : t -> row_ids:Jv.t -> unit Fut.or_error

  val apply_user_actions :
    t -> actions:Jv.t -> ?options:Jv.t -> unit -> Jv.t Fut.or_error

  val get_access_token :
    t -> ?options:Jv.t -> unit -> Access_token_result.t Fut.or_error

  val get_doc_name : t -> Jstr.t Fut.or_error
  val list_tables : t -> Jstr.t list Fut.or_error
end

module Section_API : sig
  include Jv.CONV

  val configure : t -> custom_options:Jv.t -> unit Fut.or_error
  val mappings : t -> Jv.t option Fut.or_error
end

module Widget_API : sig
  include Jv.CONV

  val clear_options : t -> unit Fut.or_error
  val get_option : t -> key:Jstr.t -> Jv.t Fut.or_error
  val get_options : t -> Jv.t option Fut.or_error
  val set_option : t -> key:Jstr.t -> value:Jv.t -> unit Fut.or_error
  val set_options : t -> options:Jv.t -> unit Fut.or_error
end

val doc_Api : Doc_API.t
val view_Api : View_API.t
val section_Api : Section_API.t
val widget_Api : Widget_API.t
val selected_table : Table_operations.t
val checkers : Jv.t
val get_table : ?table_id:Jstr.t -> unit -> Table_operations.t

val fetch_selected_record :
  row_id:int -> ?options:Jv.t -> unit -> Jv.t Fut.or_error

val fetch_selected_table : ?options:Jv.t -> unit -> Jv.t Fut.or_error
val allow_select_by : unit -> unit Fut.or_error

val get_access_token :
  ?options:Jv.t -> unit -> Access_token_result.t Fut.or_error

val clear_options : unit -> unit Fut.or_error
val get_option : key:Jstr.t -> Jv.t Fut.or_error
val get_options : unit -> Jv.t option Fut.or_error
val set_option : key:Jstr.t -> value:Jv.t -> unit Fut.or_error
val set_options : options:Jv.t -> unit Fut.or_error
val map_column_names : data:Jv.t -> ?options:Jv.t -> unit -> Jv.t
val map_column_names_back : data:Jv.t -> ?options:Jv.t -> unit -> Jv.t
val on_any : event_name:Jv.t -> listener:Jv.t -> Jv.t
val on : event_name:Jstr.t -> listener:Jv.t -> Jv.t
val on_new_record : callback:Jv.t -> unit
val on_options : callback:Jv.t -> unit
val on_record : callback:Jv.t -> ?options:Jv.t -> unit -> unit
val on_records : callback:Jv.t -> ?options:Jv.t -> unit -> unit
val ready : ?settings:Jv.t -> unit -> unit
val set_cursor_pos : pos:Jv.t -> unit Fut.or_error
val set_selected_rows : row_ids:Jv.t -> unit Fut.or_error
