(** Bindings to the Grist plugin API

    Warning: A large part of this module has been generated by a LLM without
    careful review. *)

module Data : sig
  module Row_records : sig
    include Jv.CONV

    val by_row : t -> Jv.t
  end
end

module New_record : sig
  include Jv.CONV

  val v : ?fields:(Jstr.t * Jv.t) array -> unit -> t
end

module Record : sig
  include Jv.CONV

  val v : id:int -> ?fields:(Jstr.t * Jv.t) array -> unit -> t
end

module Add_or_update_record : sig
  include Jv.CONV

  val v :
    require:(Jstr.t * Jv.t) array ->
    ?require_id:int ->
    ?fields:(Jstr.t * Jv.t) array ->
    unit ->
    t
  (** [require] is the set of column/value pairs used to match an existing
      record. [require_id] may be used to additionally match by row id. [fields]
      contains the values to write. *)
end

module Op_options : sig
  include Jv.CONV

  val v : ?parse_strings:bool -> unit -> t
end

type on_many = All | None_ | First

module Upsert_options : sig
  include Jv.CONV

  val v :
    ?add:bool ->
    ?update:bool ->
    ?on_many:on_many ->
    ?allow_empty_require:bool ->
    ?parse_strings:bool ->
    unit ->
    t
end

module Table_operations : sig
  include Jv.CONV

  val create :
    t ->
    records:New_record.t list ->
    ?options:Op_options.t ->
    unit ->
    Jv.t Fut.or_error

  val destroy : t -> record_ids:int list -> unit Fut.or_error
  val get_table_id : t -> Jstr.t Fut.or_error

  val update :
    t ->
    records:Record.t list ->
    ?options:Op_options.t ->
    unit ->
    unit Fut.or_error

  val upsert :
    t ->
    records:Add_or_update_record.t list ->
    ?options:Upsert_options.t ->
    unit ->
    unit Fut.or_error
end


module Doc_API : sig
  include Jv.CONV

  val fetch_table : table_id:Jstr.t -> Data.Row_records.t Fut.or_error
end

val doc_Api : Doc_API.t
val get_table : ?table_id:Jstr.t -> unit -> Table_operations.t
